---
- name:  unarchive_mysql_tar
  unarchive:
    src:  "{{ mysql_version }}.tar.gz"
    dest: "{{ mysql_install_path }}"
    owner: mysql
    group: mysql
  tags:
    - unarchive_mysql_tar


- name: chown_mysql
  file: 
    dest: "{{ mysql_install_path }}/{{mysql_version}}"
    owner: mysql
    group: mysql
    recurse: yes
  tags:
    - chown_mysql


- name: link_mysql
  file:
    src: "{{ mysql_install_path }}/{{mysql_version}}"
    dest: "{{ mysql_install_path }}/{{ mysql_link }}"
    owner: mysql
    group: mysql
    state: link
  tags:
    - link_mysql



- name: mkdir_log
  file:
    path: "{{ mysql_install_path }}/{{ mysql_link }}/log"
    owner: mysql
    group: mysql
    state: directory
  tags:
    - mkdir_log



- name: touch_mysql.log
  file:
    path: "{{ mysql_install_path }}/{{ mysql_link }}/log/mysqld.log"
    owner: mysql
    group: mysql
    state: touch
  tags:
    - touch_mysql.log


- name: copy_my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  tags:
    - copy_my.cnf
 


- name: init_mysql
  shell: ./bin/mysqld --initialize  --user=mysql
  args:
    chdir: "{{ mysql_install_path }}/{{ mysql_link }}"
  tags: 
    - init_mysql
    

- name: get_mysql_passwd
  shell: cat log/mysqld.log |grep localhost|awk -F ':' '{print $4}'|cut -c  2-
  register: mysql_init_passwd
  args:  
    chdir: "{{ mysql_install_path }}/{{ mysql_link }}"
  tags: 
    - get_mysql_passwd



- name: dispaly_passwd
  debug: 
    msg: "{{ mysql_init_passwd.stdout }}"
  tags:
    - dispaly_passwd



- name: copy_mysql.server
  copy:
    src: "{{ mysql_install_path }}/{{ mysql_link }}/support-files/mysql.server"
    dest: /etc/init.d/mysql-{{ mysql_port }}.server
    mode: 0755
  tags:
     - copy_mysql.server



- name: add_mysql_systemd
  template:
    src: mysql.service.j2
    dest: /etc/systemd/system/mysql-{{ mysql_port }}.service
  tags:
    - add_mysql_systemd



- name: start_mysql_service
  systemd:
    name: mysql-{{ mysql_port }}
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags:
    - start_mysql_service



- name: alter_passwd
  shell: ./bin/mysqladmin -u root -p'{{mysql_init_passwd.stdout}}' password '{{ mysql_root_passwd }}'
  args:
    chdir: "{{ mysql_install_path }}/{{ mysql_link }}"
  tags:
    - alter_passwd

